'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5485
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Messages
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ABCD.Messages", GetType(Messages).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please insert User Id!.
        '''</summary>
        Friend Shared ReadOnly Property ERR001() As String
            Get
                Return ResourceManager.GetString("ERR001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Total box is input value exceed 9999!.
        '''</summary>
        Friend Shared ReadOnly Property ERR0011() As String
            Get
                Return ResourceManager.GetString("ERR0011", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please insert Password!.
        '''</summary>
        Friend Shared ReadOnly Property ERR002() As String
            Get
                Return ResourceManager.GetString("ERR002", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid User Id!.
        '''</summary>
        Friend Shared ReadOnly Property ERR003() As String
            Get
                Return ResourceManager.GetString("ERR003", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Password!.
        '''</summary>
        Friend Shared ReadOnly Property ERR004() As String
            Get
                Return ResourceManager.GetString("ERR004", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Input quantity larger than quantity per box !.
        '''</summary>
        Friend Shared ReadOnly Property ERR00401() As String
            Get
                Return ResourceManager.GetString("ERR00401", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Input quantity larger than quantity load screen !.
        '''</summary>
        Friend Shared ReadOnly Property ERR00402() As String
            Get
                Return ResourceManager.GetString("ERR00402", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please insert Quantity !.
        '''</summary>
        Friend Shared ReadOnly Property ERR00403() As String
            Get
                Return ResourceManager.GetString("ERR00403", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please insert Quantity different from 0 !.
        '''</summary>
        Friend Shared ReadOnly Property ERR00404() As String
            Get
                Return ResourceManager.GetString("ERR00404", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please insert Lot No!.
        '''</summary>
        Friend Shared ReadOnly Property ERR00405() As String
            Get
                Return ResourceManager.GetString("ERR00405", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lot No khac voi Lot No ban dau !.
        '''</summary>
        Friend Shared ReadOnly Property ERR00406() As String
            Get
                Return ResourceManager.GetString("ERR00406", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lot No nhap vao it hon 6 ky tu !.
        '''</summary>
        Friend Shared ReadOnly Property ERR00407() As String
            Get
                Return ResourceManager.GetString("ERR00407", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please insert W/O No !.
        '''</summary>
        Friend Shared ReadOnly Property ERR00501() As String
            Get
                Return ResourceManager.GetString("ERR00501", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please insert Current Box From !.
        '''</summary>
        Friend Shared ReadOnly Property ERR00502() As String
            Get
                Return ResourceManager.GetString("ERR00502", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please insert Current Box To !.
        '''</summary>
        Friend Shared ReadOnly Property ERR00503() As String
            Get
                Return ResourceManager.GetString("ERR00503", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Current Box To must be larger than Current Box From !.
        '''</summary>
        Friend Shared ReadOnly Property ERR00504() As String
            Get
                Return ResourceManager.GetString("ERR00504", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vui lòng nhập đúng định dạng !.
        '''</summary>
        Friend Shared ReadOnly Property ERR00505() As String
            Get
                Return ResourceManager.GetString("ERR00505", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data is not found !.
        '''</summary>
        Friend Shared ReadOnly Property ERR010() As String
            Get
                Return ResourceManager.GetString("ERR010", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data is not existed !.
        '''</summary>
        Friend Shared ReadOnly Property ERR011() As String
            Get
                Return ResourceManager.GetString("ERR011", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data is existed !.
        '''</summary>
        Friend Shared ReadOnly Property ERR012() As String
            Get
                Return ResourceManager.GetString("ERR012", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No data !.
        '''</summary>
        Friend Shared ReadOnly Property ERR013() As String
            Get
                Return ResourceManager.GetString("ERR013", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Customer is being used. Can&apos;t delete data !.
        '''</summary>
        Friend Shared ReadOnly Property ERR014() As String
            Get
                Return ResourceManager.GetString("ERR014", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please insert User Id !.
        '''</summary>
        Friend Shared ReadOnly Property ERR021() As String
            Get
                Return ResourceManager.GetString("ERR021", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please insert your Current Password !.
        '''</summary>
        Friend Shared ReadOnly Property ERR022() As String
            Get
                Return ResourceManager.GetString("ERR022", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please insert New Password !.
        '''</summary>
        Friend Shared ReadOnly Property ERR023() As String
            Get
                Return ResourceManager.GetString("ERR023", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Password must have at least 6 chacracter !.
        '''</summary>
        Friend Shared ReadOnly Property ERR024() As String
            Get
                Return ResourceManager.GetString("ERR024", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please insert Confirm New Password !.
        '''</summary>
        Friend Shared ReadOnly Property ERR025() As String
            Get
                Return ResourceManager.GetString("ERR025", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Current Password !.
        '''</summary>
        Friend Shared ReadOnly Property ERR026() As String
            Get
                Return ResourceManager.GetString("ERR026", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Confirm Password does not match !.
        '''</summary>
        Friend Shared ReadOnly Property ERR027() As String
            Get
                Return ResourceManager.GetString("ERR027", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User Id must have at least 6 chacracter !.
        '''</summary>
        Friend Shared ReadOnly Property ERR029() As String
            Get
                Return ResourceManager.GetString("ERR029", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User Id is being used by system. Can&apos;t delete this User Id !.
        '''</summary>
        Friend Shared ReadOnly Property ERR030() As String
            Get
                Return ResourceManager.GetString("ERR030", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please insert User Name !.
        '''</summary>
        Friend Shared ReadOnly Property ERR031() As String
            Get
                Return ResourceManager.GetString("ERR031", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please insert Password !.
        '''</summary>
        Friend Shared ReadOnly Property ERR032() As String
            Get
                Return ResourceManager.GetString("ERR032", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select one Authority !.
        '''</summary>
        Friend Shared ReadOnly Property ERR033() As String
            Get
                Return ResourceManager.GetString("ERR033", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please insert Customer Id !.
        '''</summary>
        Friend Shared ReadOnly Property ERR041() As String
            Get
                Return ResourceManager.GetString("ERR041", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Customer Id must have at least 6 character !.
        '''</summary>
        Friend Shared ReadOnly Property ERR042() As String
            Get
                Return ResourceManager.GetString("ERR042", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please insert Customer Name !.
        '''</summary>
        Friend Shared ReadOnly Property ERR043() As String
            Get
                Return ResourceManager.GetString("ERR043", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Customer Name must have at least 6 character !.
        '''</summary>
        Friend Shared ReadOnly Property ERR044() As String
            Get
                Return ResourceManager.GetString("ERR044", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please insert Address !.
        '''</summary>
        Friend Shared ReadOnly Property ERR045() As String
            Get
                Return ResourceManager.GetString("ERR045", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select Destination !.
        '''</summary>
        Friend Shared ReadOnly Property ERR046() As String
            Get
                Return ResourceManager.GetString("ERR046", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please insert Item Code !.
        '''</summary>
        Friend Shared ReadOnly Property ERR047() As String
            Get
                Return ResourceManager.GetString("ERR047", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Item Code must have at least 6 character !.
        '''</summary>
        Friend Shared ReadOnly Property ERR048() As String
            Get
                Return ResourceManager.GetString("ERR048", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please insert Item Name !.
        '''</summary>
        Friend Shared ReadOnly Property ERR049() As String
            Get
                Return ResourceManager.GetString("ERR049", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Item Name must have at least 6 character !.
        '''</summary>
        Friend Shared ReadOnly Property ERR050() As String
            Get
                Return ResourceManager.GetString("ERR050", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please insert Quantity different from 0 !.
        '''</summary>
        Friend Shared ReadOnly Property ERR051() As String
            Get
                Return ResourceManager.GetString("ERR051", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select Template !.
        '''</summary>
        Friend Shared ReadOnly Property ERR052() As String
            Get
                Return ResourceManager.GetString("ERR052", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select Unit !.
        '''</summary>
        Friend Shared ReadOnly Property ERR053() As String
            Get
                Return ResourceManager.GetString("ERR053", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please insert or select Item Code !.
        '''</summary>
        Friend Shared ReadOnly Property ERR054() As String
            Get
                Return ResourceManager.GetString("ERR054", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select Warehouse Code !.
        '''</summary>
        Friend Shared ReadOnly Property ERR055() As String
            Get
                Return ResourceManager.GetString("ERR055", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Item Code is being used. Can&apos;t delete it !.
        '''</summary>
        Friend Shared ReadOnly Property ERR056() As String
            Get
                Return ResourceManager.GetString("ERR056", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select date for W/O Date !.
        '''</summary>
        Friend Shared ReadOnly Property ERR057() As String
            Get
                Return ResourceManager.GetString("ERR057", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please insert Product Quantity !.
        '''</summary>
        Friend Shared ReadOnly Property ERR058() As String
            Get
                Return ResourceManager.GetString("ERR058", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please insert Product Quantity different from 0 !.
        '''</summary>
        Friend Shared ReadOnly Property ERR059() As String
            Get
                Return ResourceManager.GetString("ERR059", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please insert Quantity Per Box !.
        '''</summary>
        Friend Shared ReadOnly Property ERR060() As String
            Get
                Return ResourceManager.GetString("ERR060", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please insert Quantity Per Box different from 0 !.
        '''</summary>
        Friend Shared ReadOnly Property ERR061() As String
            Get
                Return ResourceManager.GetString("ERR061", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to W/O No is issued. Can not modify or delete !.
        '''</summary>
        Friend Shared ReadOnly Property ERR062() As String
            Get
                Return ResourceManager.GetString("ERR062", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please insert W/O No !.
        '''</summary>
        Friend Shared ReadOnly Property ERR063() As String
            Get
                Return ResourceManager.GetString("ERR063", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to W/O No must have at least 10 character !.
        '''</summary>
        Friend Shared ReadOnly Property ERR064() As String
            Get
                Return ResourceManager.GetString("ERR064", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please choose valid Item Code !.
        '''</summary>
        Friend Shared ReadOnly Property ERR065() As String
            Get
                Return ResourceManager.GetString("ERR065", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Incompleted Import Data !.
        '''</summary>
        Friend Shared ReadOnly Property ERR068() As String
            Get
                Return ResourceManager.GetString("ERR068", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please insert Quantity !.
        '''</summary>
        Friend Shared ReadOnly Property ERR069() As String
            Get
                Return ResourceManager.GetString("ERR069", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please insert Orotex No !.
        '''</summary>
        Friend Shared ReadOnly Property ERR070() As String
            Get
                Return ResourceManager.GetString("ERR070", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Don&apos;t have box is not enough quantity !.
        '''</summary>
        Friend Shared ReadOnly Property INF00408() As String
            Get
                Return ResourceManager.GetString("INF00408", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to W/O No have only box not enough quantity !.
        '''</summary>
        Friend Shared ReadOnly Property INF00409() As String
            Get
                Return ResourceManager.GetString("INF00409", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Change Password successfully !.
        '''</summary>
        Friend Shared ReadOnly Property INF028() As String
            Get
                Return ResourceManager.GetString("INF028", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Added successfully !.
        '''</summary>
        Friend Shared ReadOnly Property INF036() As String
            Get
                Return ResourceManager.GetString("INF036", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Updated successfully !.
        '''</summary>
        Friend Shared ReadOnly Property INF038() As String
            Get
                Return ResourceManager.GetString("INF038", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Deleted successfully !.
        '''</summary>
        Friend Shared ReadOnly Property INF040() As String
            Get
                Return ResourceManager.GetString("INF040", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Completed Import Data !.
        '''</summary>
        Friend Shared ReadOnly Property INF067() As String
            Get
                Return ResourceManager.GetString("INF067", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to open this file ?.
        '''</summary>
        Friend Shared ReadOnly Property MSG002() As String
            Get
                Return ResourceManager.GetString("MSG002", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to update information of Label ?.
        '''</summary>
        Friend Shared ReadOnly Property MSG00401() As String
            Get
                Return ResourceManager.GetString("MSG00401", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to add this?.
        '''</summary>
        Friend Shared ReadOnly Property MSG035() As String
            Get
                Return ResourceManager.GetString("MSG035", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to change this?.
        '''</summary>
        Friend Shared ReadOnly Property MSG037() As String
            Get
                Return ResourceManager.GetString("MSG037", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to delete this?.
        '''</summary>
        Friend Shared ReadOnly Property MSG039() As String
            Get
                Return ResourceManager.GetString("MSG039", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Previous Stocktaking Data will be deleted !.
        '''</summary>
        Friend Shared ReadOnly Property MSG066() As String
            Get
                Return ResourceManager.GetString("MSG066", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please input at least one condition !.
        '''</summary>
        Friend Shared ReadOnly Property PRS002_01() As String
            Get
                Return ResourceManager.GetString("PRS002_01", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please check value date from and date to !.
        '''</summary>
        Friend Shared ReadOnly Property PRS002_02() As String
            Get
                Return ResourceManager.GetString("PRS002_02", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please input Product Quantity !.
        '''</summary>
        Friend Shared ReadOnly Property PRS002_03() As String
            Get
                Return ResourceManager.GetString("PRS002_03", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please input Product Quantity is Number !.
        '''</summary>
        Friend Shared ReadOnly Property PRS002_04() As String
            Get
                Return ResourceManager.GetString("PRS002_04", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Product Quantity exceeded the limit !.
        '''</summary>
        Friend Shared ReadOnly Property PRS002_05() As String
            Get
                Return ResourceManager.GetString("PRS002_05", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please input Product Date !.
        '''</summary>
        Friend Shared ReadOnly Property PRS002_06() As String
            Get
                Return ResourceManager.GetString("PRS002_06", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please input Product Date with format &quot;dd/MM/yyyy&quot; !.
        '''</summary>
        Friend Shared ReadOnly Property PRS002_07() As String
            Get
                Return ResourceManager.GetString("PRS002_07", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please check System Date and Product Date !.
        '''</summary>
        Friend Shared ReadOnly Property PRS002_08() As String
            Get
                Return ResourceManager.GetString("PRS002_08", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to execute this process ?.
        '''</summary>
        Friend Shared ReadOnly Property PRS002_09() As String
            Get
                Return ResourceManager.GetString("PRS002_09", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Click OK for exporting Label information !.
        '''</summary>
        Friend Shared ReadOnly Property PRS002_10() As String
            Get
                Return ResourceManager.GetString("PRS002_10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Not allow to input decreased quantity !.
        '''</summary>
        Friend Shared ReadOnly Property PRS004_04() As String
            Get
                Return ResourceManager.GetString("PRS004_04", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Not allow to input exceeded quantity !.
        '''</summary>
        Friend Shared ReadOnly Property PRS004_05() As String
            Get
                Return ResourceManager.GetString("PRS004_05", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
